# Generated by Django 2.0 on 2019-02-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='favorite_color',
            field=models.CharField(default='black', max_length=16),
        ),
    ]
