# Generated by Django 2.0 on 2019-02-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superheroes', '0002_superhero_favorite_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='superhero',
            name='favorite_ice_cream',
            field=models.CharField(default='Cherry Garcia', max_length=32),
        ),
    ]
